### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Prolucid/fable-ga#1]
Hi @et1975! I'm doing some cleanup of repositories under fable-compiler org. Would it be ok to move this to your GH profile? Thanks!

**Comment by et1975** [comment]
Sure!

**Comment by alfonsogarciacaro** [comment]
Thanks! It seems that you need to do it yourself. Can you do it or do you need some special rights?

**Comment by et1975** [comment]
I'll do it.

**Comment by et1975** [comment]
Ditto on permissions.

**Comment by alfonsogarciacaro** [comment]
Sorry, forgot this one. Done!
